"use client";

import { FormEvent, useCallback, useEffect, useState } from "react";
import { BarChart3, IndianRupee, LoaderCircle, Pencil, Plus, Trash2, TrendingDown, TrendingUp, Users } from "lucide-react";
import { toast } from "sonner";

import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { EVENT_EXPENSE_CATEGORIES, eventFinanceService, type EventExpense, type EventExpenseInput, type EventProfitability } from "@/services/event-finance.service";
import type { StudioEvent } from "@/services/events.service";

const money = new Intl.NumberFormat("en-IN", { style: "currency", currency: "INR", maximumFractionDigits: 2 });
const today = () => { const date = new Date(); return `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, "0")}-${String(date.getDate()).padStart(2, "0")}`; };
const empty = (): EventExpenseInput => ({ category: "Venue", description: "", amount: 0, expense_date: today(), payment_method: "", reference_number: "" });

function Metric({ label, value, detail, icon: Icon, tone = "text-foreground" }: { label: string; value: string; detail?: string; icon: typeof IndianRupee; tone?: string }) {
  return <div className="rounded-xl border bg-card p-3"><div className="flex items-center gap-2 text-xs text-muted-foreground"><Icon className="size-4" />{label}</div><p className={`mt-1 text-lg font-semibold ${tone}`}>{value}</p>{detail && <p className="text-xs text-muted-foreground">{detail}</p>}</div>;
}

export default function EventAnalyticsDialog({ eventItem, open, onOpenChange, onChanged }: { eventItem: StudioEvent | null; open: boolean; onOpenChange: (open: boolean) => void; onChanged: () => void }) {
  const [expenses, setExpenses] = useState<EventExpense[]>([]); const [analytics, setAnalytics] = useState<EventProfitability | null>(null); const [form, setForm] = useState<EventExpenseInput>(empty); const [editing, setEditing] = useState<EventExpense | null>(null); const [loading, setLoading] = useState(false); const [saving, setSaving] = useState(false); const [error, setError] = useState("");
  const load = useCallback(async () => { if (!eventItem) return; setLoading(true); setError(""); try { const [expenseRows, result] = await Promise.all([eventFinanceService.getExpenses(eventItem.id), eventFinanceService.getProfitability(eventItem.id, eventItem.max_capacity)]); setExpenses(expenseRows); setAnalytics(result); } catch (caught) { setError(caught instanceof Error ? caught.message : "Unable to load event analytics."); } finally { setLoading(false); } }, [eventItem]);
  useEffect(() => {
    if (!open) return;
    // eslint-disable-next-line react-hooks/set-state-in-effect
    setEditing(null);
    setForm(empty());
    void load();
  }, [open, load]);
  function edit(item: EventExpense) { setEditing(item); setForm({ category: item.category, description: item.description, amount: item.amount, expense_date: item.expense_date, payment_method: item.payment_method ?? "", reference_number: item.reference_number ?? "" }); }
  function reset() { setEditing(null); setForm(empty()); }
  async function submit(event: FormEvent) { event.preventDefault(); if (!eventItem) return; setSaving(true); try { if (editing) await eventFinanceService.updateExpense(editing.id, form); else await eventFinanceService.createExpense(eventItem.id, form); toast.success(editing ? "Event expense updated." : "Event expense added."); reset(); await load(); onChanged(); } catch (caught) { toast.error(caught instanceof Error ? caught.message : "Unable to save event expense."); } finally { setSaving(false); } }
  async function remove(item: EventExpense) { if (!window.confirm(`Delete the ${item.description} expense of ${money.format(item.amount)}?`)) return; try { await eventFinanceService.removeExpense(item.id); toast.success("Event expense deleted."); if (editing?.id === item.id) reset(); await load(); onChanged(); } catch (caught) { toast.error(caught instanceof Error ? caught.message : "Unable to delete event expense."); } }
  return <Dialog open={open} onOpenChange={(next) => !saving && onOpenChange(next)}><DialogContent className="sm:max-w-4xl"><DialogHeader><DialogTitle>{eventItem?.title ?? "Event"} analytics</DialogTitle><DialogDescription>Track event costs, attendance and profitability. These figures are kept separate from membership payments.</DialogDescription></DialogHeader>
    {loading ? <div className="py-12 text-center text-muted-foreground">Loading event analytics...</div> : error ? <div className="rounded-xl border border-destructive/30 bg-destructive/5 p-4 text-destructive">{error}<Button className="ml-3" size="sm" variant="outline" onClick={() => void load()}>Retry</Button></div> : <div className="space-y-5">
      {analytics && <div className="grid grid-cols-2 gap-3 lg:grid-cols-4"><Metric label="Net collected" value={money.format(analytics.netRevenue)} detail={`${money.format(analytics.grossRevenue)} gross · ${money.format(analytics.refunds)} refunded`} icon={IndianRupee} /><Metric label="Event expenses" value={money.format(analytics.expenses)} icon={TrendingDown} tone="text-orange-600" /><Metric label="Profit" value={money.format(analytics.profit)} detail={analytics.profit >= 0 ? "Net collected minus costs" : "Costs exceed net collected"} icon={analytics.profit >= 0 ? TrendingUp : TrendingDown} tone={analytics.profit >= 0 ? "text-emerald-600" : "text-destructive"} /><Metric label="Attendance" value={`${analytics.attendees}/${analytics.registrations}`} detail={`${analytics.attendanceRate}% attendance · ${analytics.capacityUsage}% capacity`} icon={Users} /><Metric label="Per attendee" value={money.format(analytics.averageRevenuePerAttendee)} detail="Net revenue per checked-in participant" icon={BarChart3} /></div>}
      <form onSubmit={submit} className="rounded-xl border p-4"><div className="mb-3 flex items-center justify-between"><h3 className="font-semibold">{editing ? "Edit expense" : "Add event expense"}</h3>{editing && <Button type="button" size="sm" variant="ghost" onClick={reset}>Cancel edit</Button>}</div><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><div className="space-y-1.5"><Label>Category</Label><Select value={form.category} onValueChange={(value) => setForm((current) => ({ ...current, category: value ?? "Other" }))}><SelectTrigger className="w-full"><SelectValue /></SelectTrigger><SelectContent>{EVENT_EXPENSE_CATEGORIES.map((item) => <SelectItem key={item} value={item}>{item}</SelectItem>)}</SelectContent></Select></div><div className="space-y-1.5 sm:col-span-2"><Label htmlFor="expense-description">Description</Label><Input id="expense-description" required maxLength={200} placeholder="Venue rent, instructor fee..." value={form.description} onChange={(event) => setForm((current) => ({ ...current, description: event.target.value }))} /></div><div className="space-y-1.5"><Label htmlFor="expense-amount">Amount (₹)</Label><Input id="expense-amount" required type="number" min="0.01" step="0.01" value={form.amount || ""} onChange={(event) => setForm((current) => ({ ...current, amount: Number(event.target.value) }))} /></div><div className="space-y-1.5"><Label htmlFor="expense-date">Date</Label><Input id="expense-date" required type="date" value={form.expense_date} onChange={(event) => setForm((current) => ({ ...current, expense_date: event.target.value }))} /></div><div className="space-y-1.5"><Label htmlFor="expense-method">Payment method</Label><Input id="expense-method" maxLength={50} placeholder="UPI, Cash..." value={form.payment_method ?? ""} onChange={(event) => setForm((current) => ({ ...current, payment_method: event.target.value }))} /></div><div className="space-y-1.5 lg:col-span-2"><Label htmlFor="expense-reference">Reference (optional)</Label><Input id="expense-reference" maxLength={100} value={form.reference_number ?? ""} onChange={(event) => setForm((current) => ({ ...current, reference_number: event.target.value }))} /></div></div><div className="mt-3 flex justify-end"><Button type="submit" disabled={saving}>{saving ? <LoaderCircle className="animate-spin" /> : <Plus />}{editing ? "Update expense" : "Add expense"}</Button></div></form>
      <div><h3 className="mb-2 font-semibold">Expense history</h3>{expenses.length === 0 ? <p className="rounded-xl border border-dashed p-6 text-center text-sm text-muted-foreground">No expenses recorded for this event.</p> : <div className="space-y-2">{expenses.map((item) => <div key={item.id} className="flex flex-col gap-2 rounded-xl border p-3 sm:flex-row sm:items-center sm:justify-between"><div><p className="font-medium">{item.description}</p><p className="text-xs text-muted-foreground">{item.category} · {item.expense_date}{item.payment_method ? ` · ${item.payment_method}` : ""}{item.reference_number ? ` · ${item.reference_number}` : ""}</p></div><div className="flex items-center gap-2"><strong>{money.format(item.amount)}</strong><Button type="button" size="icon-sm" variant="outline" aria-label="Edit expense" onClick={() => edit(item)}><Pencil /></Button><Button type="button" size="icon-sm" variant="outline" className="text-destructive" aria-label="Delete expense" onClick={() => void remove(item)}><Trash2 /></Button></div></div>)}</div>}</div>
    </div>}<DialogFooter><Button type="button" variant="outline" onClick={() => onOpenChange(false)}>Close</Button></DialogFooter></DialogContent></Dialog>;
}
