"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import { CheckCircle2, Clock3, Download, LoaderCircle, MessageCircle, Printer, Search, UserCheck, Users, XCircle } from "lucide-react";
import { toast } from "sonner";

import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { eventAttendanceService, type EventAttendee, type EventCheckInStatus } from "@/services/event-attendance.service";
import type { StudioEvent } from "@/services/events.service";

function whatsappPhone(phone: string) { const digits = phone.replace(/\D/g, ""); return digits.length === 10 ? `91${digits}` : digits; }
function csvCell(value: unknown) { const text = String(value ?? ""); const safe = /^[=+\-@]/.test(text) ? `'${text}` : text; return `"${safe.replaceAll('"', '""')}"`; }
function localDate(date: string) { return new Intl.DateTimeFormat("en-IN", { dateStyle: "long" }).format(new Date(`${date}T00:00:00`)); }
function localTime(time: string) { return new Intl.DateTimeFormat("en-IN", { hour: "numeric", minute: "2-digit" }).format(new Date(`2000-01-01T${time}:00`)); }

export default function EventCheckInDialog({ open, eventItem, onOpenChange }: { open: boolean; eventItem: StudioEvent | null; onOpenChange: (open: boolean) => void }) {
  const [items, setItems] = useState<EventAttendee[]>([]);
  const [search, setSearch] = useState("");
  const [loading, setLoading] = useState(false);
  const [savingId, setSavingId] = useState<number | null>(null);
  const [error, setError] = useState("");

  const load = useCallback(async () => { if (!eventItem) return; setLoading(true); setError(""); try { setItems(await eventAttendanceService.getByEvent(eventItem.id)); } catch (caught) { setError(caught instanceof Error ? caught.message : "Unable to load check-in."); } finally { setLoading(false); } }, [eventItem]);
  useEffect(() => {
    if (!open) return;
    // eslint-disable-next-line react-hooks/set-state-in-effect
    void load();
  }, [open, load]);
  const filtered = useMemo(() => { const query = search.trim().toLowerCase(); return items.filter((item) => `${item.participant_name} ${item.registration.phone} ${item.attendance_status}`.toLowerCase().includes(query)); }, [items, search]);
  const attended = items.filter((item) => item.attendance_status === "Attended").length;
  const noShows = items.filter((item) => item.attendance_status === "No Show").length;

  async function update(item: EventAttendee, status: EventCheckInStatus, group = false) { setSavingId(item.id); try { if (group) await eventAttendanceService.setRegistrationStatus(item.registration_id, status); else await eventAttendanceService.setStatus(item.id, status); toast.success(group ? "Group attendance updated." : `${item.participant_name} marked ${status.toLowerCase()}.`); await load(); } catch (caught) { toast.error(caught instanceof Error ? caught.message : "Unable to update attendance."); } finally { setSavingId(null); } }
  function downloadCsv() { if (!eventItem) return; const header = ["Participant", "Primary contact", "Phone", "Payment", "Attendance", "Check-in time"]; const rows = items.map((item) => [item.participant_name, item.registration.participant_name, item.registration.phone, item.registration.payment_status, item.attendance_status, item.checked_in_at ? new Date(item.checked_in_at).toLocaleString("en-IN") : ""]); const blob = new Blob([[header, ...rows].map((row) => row.map(csvCell).join(",")).join("\r\n")], { type: "text/csv;charset=utf-8" }); const url = URL.createObjectURL(blob); const link = document.createElement("a"); link.href = url; link.download = `${eventItem.title.replace(/[^a-z0-9]+/gi, "-").toLowerCase()}-participants.csv`; link.click(); URL.revokeObjectURL(url); }
  function printRegister() { if (!eventItem) return; const popup = window.open("", "_blank"); if (!popup) { toast.error("Allow pop-ups, then try again."); return; } const doc = popup.document; doc.title = `${eventItem.title} attendance register`; const style = doc.createElement("style"); style.textContent = "body{font-family:Arial,sans-serif;margin:32px;color:#111}h1{margin-bottom:4px}p{color:#555}table{width:100%;border-collapse:collapse;margin-top:24px}th,td{border:1px solid #bbb;padding:8px;text-align:left}th{background:#eee}@media print{body{margin:0}}"; doc.head.append(style); const title = doc.createElement("h1"); title.textContent = eventItem.title; doc.body.append(title); const details = doc.createElement("p"); details.textContent = `${localDate(eventItem.event_date)} · ${localTime(eventItem.start_time)} · ${eventItem.location}`; doc.body.append(details); const table = doc.createElement("table"); const head = table.createTHead().insertRow(); ["#", "Participant", "Phone", "Payment", "Attendance", "Signature"].forEach((value) => { const cell = doc.createElement("th"); cell.textContent = value; head.append(cell); }); const body = table.createTBody(); items.forEach((item, index) => { const row = body.insertRow(); [String(index + 1), item.participant_name, item.registration.phone, item.registration.payment_status, item.attendance_status, ""].forEach((value) => { const cell = row.insertCell(); cell.textContent = value; }); }); doc.body.append(table); popup.addEventListener("afterprint", () => popup.close(), { once: true }); popup.focus(); popup.print(); }
  function reminder(item: EventAttendee, payment = false) { if (!eventItem) return "#"; const text = payment ? `Hi ${item.registration.participant_name}, a payment of ₹${Number(item.registration.amount_due ?? 0).toLocaleString("en-IN")} is pending for ${eventItem.title}. Please complete it before the event. — Footloose Alley` : `Hi ${item.registration.participant_name}, reminder for ${eventItem.title} on ${localDate(eventItem.event_date)} at ${localTime(eventItem.start_time)}, ${eventItem.location}. See you there! — Footloose Alley`; return `https://wa.me/${whatsappPhone(item.registration.phone)}?text=${encodeURIComponent(text)}`; }

  return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="max-h-[calc(100dvh-1rem)] overflow-y-auto sm:max-w-5xl"><DialogHeader><DialogTitle>{eventItem?.title ?? "Event"} check-in</DialogTitle><DialogDescription>Check in individuals or complete groups, send reminders, and export the event register.</DialogDescription></DialogHeader>
    <div className="grid grid-cols-2 gap-2 sm:grid-cols-4"><div className="rounded-xl bg-muted/50 p-3"><Users className="size-4 text-primary" /><strong className="mt-1 block text-xl">{items.length}</strong><span className="text-xs">Participants</span></div><div className="rounded-xl bg-emerald-50 p-3"><UserCheck className="size-4 text-emerald-700" /><strong className="mt-1 block text-xl">{attended}</strong><span className="text-xs">Checked in</span></div><div className="rounded-xl bg-amber-50 p-3"><Clock3 className="size-4 text-amber-700" /><strong className="mt-1 block text-xl">{Math.max(0, items.length - attended - noShows)}</strong><span className="text-xs">Remaining</span></div><div className="rounded-xl bg-red-50 p-3"><XCircle className="size-4 text-red-700" /><strong className="mt-1 block text-xl">{noShows}</strong><span className="text-xs">No show</span></div></div>
    <div className="flex flex-col gap-2 sm:flex-row"><label className="relative flex-1"><Search className="pointer-events-none absolute left-3 top-1/2 size-4 -translate-y-1/2 text-muted-foreground" /><Input className="h-11 pl-9" placeholder="Search name or phone" value={search} onChange={(event) => setSearch(event.target.value)} /></label><Button type="button" variant="outline" className="h-11" onClick={downloadCsv}><Download /> CSV</Button><Button type="button" variant="outline" className="h-11" onClick={printRegister}><Printer /> Print register</Button></div>
    {loading ? <p className="py-10 text-center text-sm text-muted-foreground"><LoaderCircle className="mx-auto mb-2 animate-spin" />Loading check-in…</p> : error ? <p role="alert" className="rounded-xl bg-destructive/10 p-4 text-sm text-destructive">{error}</p> : filtered.length === 0 ? <p className="py-10 text-center text-sm text-muted-foreground">No participants match this search.</p> : <div className="space-y-3">{filtered.map((item) => <article key={item.id} className="rounded-2xl border p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><h3 className="font-semibold">{item.participant_name}{item.is_primary && <span className="ml-2 text-xs text-primary">Primary</span>}</h3><p className="mt-1 text-sm text-muted-foreground">{item.registration.phone} · {item.registration.payment_status}</p>{item.checked_in_at && <p className="mt-1 text-xs text-emerald-700">Checked in {new Date(item.checked_in_at).toLocaleTimeString("en-IN", { hour: "numeric", minute: "2-digit" })}</p>}</div><span className="rounded-full bg-muted px-2.5 py-1 text-xs font-semibold">{item.attendance_status}</span></div><div className="mt-3 flex flex-wrap gap-2"><Button type="button" size="sm" disabled={savingId === item.id} onClick={() => void update(item, "Attended")}><CheckCircle2 /> Check in</Button><Button type="button" size="sm" variant="outline" disabled={savingId === item.id} onClick={() => void update(item, "Registered")}>Undo</Button><Button type="button" size="sm" variant="outline" disabled={savingId === item.id} onClick={() => void update(item, "No Show")}>No show</Button>{item.is_primary && items.filter((other) => other.registration_id === item.registration_id).length > 1 && <Button type="button" size="sm" variant="outline" disabled={savingId === item.id} onClick={() => void update(item, "Attended", true)}><Users /> Check in group</Button>}{item.is_primary && <><Button size="sm" variant="outline" render={<a href={reminder(item)} target="_blank" rel="noreferrer" />}><MessageCircle /> Event reminder</Button>{item.registration.payment_status === "Pending" && <Button size="sm" variant="outline" render={<a href={reminder(item, true)} target="_blank" rel="noreferrer" />}><MessageCircle /> Payment reminder</Button>}</>}</div></article>)}</div>}
  </DialogContent></Dialog>;
}
