"use client";
import { useCallback,useEffect,useState } from "react"; import { CalendarDays,CheckCircle2,MessageCircle,PartyPopper,Plus,RefreshCw,XCircle } from "lucide-react"; import { toast } from "sonner";
import ErrorCard from "@/components/common/ErrorCard"; import LoadingCard from "@/components/common/LoadingCard"; import PageHeader from "@/components/layout/PageHeader"; import StatCard from "@/components/ui-foundation/StatCard"; import { Badge } from "@/components/ui/badge"; import { Button } from "@/components/ui/button"; import { Card,CardContent,CardHeader,CardTitle } from "@/components/ui/card"; import { Input } from "@/components/ui/input"; import { Select,SelectContent,SelectItem,SelectTrigger,SelectValue } from "@/components/ui/select";
import { EVENT_STATUSES,EVENT_TYPES,eventsService,type EventStatus,type StudioEvent } from "@/services/events.service"; import EventFormDialog from "./EventFormDialog";
const money=new Intl.NumberFormat("en-IN",{style:"currency",currency:"INR",maximumFractionDigits:2}); const friendlyDate=(date:string)=>new Intl.DateTimeFormat("en-IN",{dateStyle:"long"}).format(new Date(`${date}T00:00:00`)); const friendlyTime=(time:string)=>new Intl.DateTimeFormat("en-IN",{hour:"numeric",minute:"2-digit"}).format(new Date(`2000-01-01T${time}:00`));
function localCalendarDate(date=new Date()){const year=date.getFullYear(),month=String(date.getMonth()+1).padStart(2,"0"),day=String(date.getDate()).padStart(2,"0");return `${year}-${month}-${day}`}
export default function EventsManagement(){const [items,setItems]=useState<StudioEvent[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(""),[search,setSearch]=useState(""),[status,setStatus]=useState("All"),[type,setType]=useState("All"),[scope,setScope]=useState("All"),[open,setOpen]=useState(false),[editing,setEditing]=useState<StudioEvent|null>(null),[savingId,setSavingId]=useState<number|null>(null);
 const load=useCallback(async()=>{setLoading(true);setError("");try{setItems(await eventsService.getAll())}catch(e){setError(e instanceof Error?e.message:"Unable to load events.")}finally{setLoading(false)}},[]); useEffect(()=>{
   // Initial remote-data synchronization.
   // eslint-disable-next-line react-hooks/set-state-in-effect
   void load()
 },[load]); const today=localCalendarDate(),month=today.slice(0,7);
 const filtered=items.filter(item=>{const q=search.trim().toLowerCase();return(!q||`${item.title} ${item.event_type} ${item.location} ${item.description??""}`.toLowerCase().includes(q))&&(status==="All"||item.status===status)&&(type==="All"||item.event_type===type)&&(scope==="All"||(scope==="Upcoming"?item.event_date>=today:item.event_date<today))});
 async function change(item:StudioEvent,next:EventStatus){setSavingId(item.id);try{await eventsService.setStatus(item.id,next);toast.success(`Event marked ${next.toLowerCase()}.`);await load()}catch(e){toast.error(e instanceof Error?e.message:"Unable to change event status.")}finally{setSavingId(null)}}
 function share(item:StudioEvent){const fee=Number(item.fee)===0?"Free":money.format(Number(item.fee)),contact=item.contact_phone||"8884978589",studioContact=contact!=="8884978589"?"\nFootloose Alley: 8884978589":"";const text=`${item.title}\nDate: ${friendlyDate(item.event_date)}\nTime: ${friendlyTime(item.start_time)} – ${friendlyTime(item.end_time)}\nLocation: ${item.location}\nFee: ${fee}\nContact: ${contact}${studioContact}`;window.open(`https://wa.me/?text=${encodeURIComponent(text)}`,"_blank","noopener,noreferrer")}
 return <div className="space-y-6"><PageHeader title="Events Management" description="Plan, publish, and manage every Footloose Alley event." action={<Button type="button" onClick={()=>{setEditing(null);setOpen(true)}}><Plus/> Add Event</Button>}/><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><StatCard label="Total upcoming" value={items.filter(x=>x.status==="Upcoming"&&x.event_date>=today).length} icon={PartyPopper}/><StatCard label="Events this month" value={items.filter(x=>x.event_date.startsWith(month)).length} icon={CalendarDays}/><StatCard label="Completed" value={items.filter(x=>x.status==="Completed").length} icon={CheckCircle2}/><StatCard label="Cancelled" value={items.filter(x=>x.status==="Cancelled").length} icon={XCircle}/></div>
 <section className="space-y-4 rounded-2xl border bg-card p-4"><div className="grid gap-3 md:grid-cols-4"><Input aria-label="Search events" placeholder="Search events…" value={search} onChange={e=>setSearch(e.target.value)}/><Select value={status} onValueChange={v=>v&&setStatus(v)}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="All">All statuses</SelectItem>{EVENT_STATUSES.map(v=><SelectItem key={v} value={v}>{v}</SelectItem>)}</SelectContent></Select><Select value={type} onValueChange={v=>v&&setType(v)}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="All">All types</SelectItem>{EVENT_TYPES.map(v=><SelectItem key={v} value={v}>{v}</SelectItem>)}</SelectContent></Select><Select value={scope} onValueChange={v=>v&&setScope(v)}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{["All","Upcoming","Past"].map(v=><SelectItem key={v} value={v}>{v} dates</SelectItem>)}</SelectContent></Select></div><div className="flex justify-end"><Button type="button" variant="ghost" size="sm" onClick={()=>void load()} disabled={loading}><RefreshCw className={loading?"animate-spin":""}/> Refresh</Button></div></section>
 {loading?<LoadingCard/>:error?<ErrorCard message={error} onRetry={()=>void load()}/>:filtered.length===0?<Card><CardContent className="py-12 text-center text-muted-foreground">No events match these filters.</CardContent></Card>:<div className="grid gap-4 lg:grid-cols-2">{filtered.map(item=><Card key={item.id}><CardHeader className="gap-2"><div className="flex items-start justify-between gap-3"><CardTitle>{item.title}</CardTitle><Badge variant="secondary">{item.status}</Badge></div><p className="text-sm font-medium text-primary">{item.event_type}</p></CardHeader><CardContent className="space-y-3"><div className="grid gap-1 text-sm sm:grid-cols-2"><p><b>Date:</b> {friendlyDate(item.event_date)}</p><p><b>Time:</b> {friendlyTime(item.start_time)} – {friendlyTime(item.end_time)}</p><p><b>Location:</b> {item.location}</p><p><b>Fee:</b> {Number(item.fee)===0?"Free":money.format(Number(item.fee))}</p><p><b>Capacity:</b> {item.max_capacity}</p></div>{item.description&&<p className="text-sm text-muted-foreground">{item.description}</p>}<div className="flex flex-wrap gap-2"><Button type="button" size="sm" variant="outline" onClick={()=>{setEditing(item);setOpen(true)}}>Edit</Button><Button type="button" size="sm" variant="outline" onClick={()=>share(item)}><MessageCircle/> Share on WhatsApp</Button>{item.status==="Upcoming"&&<><Button type="button" size="sm" onClick={()=>void change(item,"Completed")} disabled={savingId===item.id}>Mark Completed</Button><Button type="button" size="sm" variant="destructive" onClick={()=>void change(item,"Cancelled")} disabled={savingId===item.id}>Cancel Event</Button></>}{(item.status==="Completed"||item.status==="Cancelled")&&<Button type="button" size="sm" onClick={()=>void change(item,"Upcoming")} disabled={savingId===item.id}>Reopen as Upcoming</Button>}</div></CardContent></Card>)}</div>}
 <EventFormDialog open={open} eventItem={editing} onOpenChange={next=>{setOpen(next);if(!next)setEditing(null)}} onSaved={()=>void load()}/></div>}
