"use client";
import { FormEvent, useEffect, useState } from "react";
import { LoaderCircle } from "lucide-react"; import { toast } from "sonner";
import { Button } from "@/components/ui/button"; import { Dialog,DialogContent,DialogDescription,DialogHeader,DialogTitle } from "@/components/ui/dialog"; import { Input } from "@/components/ui/input"; import { Label } from "@/components/ui/label"; import { Textarea } from "@/components/ui/textarea"; import { Select,SelectContent,SelectItem,SelectTrigger,SelectValue } from "@/components/ui/select";
import { EVENT_STATUSES,EVENT_TYPES,eventsService,type EventInput,type StudioEvent } from "@/services/events.service";
interface Props{open:boolean;eventItem:StudioEvent|null;onOpenChange:(open:boolean)=>void;onSaved:()=>void}
const defaults:EventInput={title:"",event_type:"Special Class",event_date:"",start_time:"10:00",end_time:"11:00",location:"Footloose Alley",max_capacity:50,fee:0,status:"Upcoming",contact_phone:"8884978589",description:"",notes:""};
function initial(item:StudioEvent|null):EventInput{return item?{title:item.title,event_type:item.event_type,event_date:item.event_date,start_time:item.start_time,end_time:item.end_time,location:item.location,max_capacity:item.max_capacity,fee:Number(item.fee),status:item.status,contact_phone:item.contact_phone??"",description:item.description??"",notes:item.notes??""}:{...defaults}}
export default function EventFormDialog({open,eventItem,onOpenChange,onSaved}:Props){const [form,setForm]=useState<EventInput>(()=>initial(eventItem)),[saving,setSaving]=useState(false),[error,setError]=useState("");
 useEffect(()=>{if(open){
   // Reset from persisted data or defaults whenever the controlled dialog opens.
   // eslint-disable-next-line react-hooks/set-state-in-effect
   setForm(initial(eventItem));setError("")}},[open,eventItem]);
 function close(next:boolean){if(!next){setError("");setForm(initial(eventItem))}onOpenChange(next)}
 async function submit(e:FormEvent){e.preventDefault();setSaving(true);setError("");try{if(eventItem)await eventsService.update(eventItem.id,form);else await eventsService.create(form);toast.success(eventItem?"Event updated.":"Event added.");close(false);onSaved()}catch(c){const message=c instanceof Error?c.message:"Unable to save event.";setError(message);toast.error(message)}finally{setSaving(false)}}
 const field=(key:keyof EventInput,value:string|number)=>setForm(current=>({...current,[key]:value}));
 return <Dialog open={open} onOpenChange={close}><DialogContent className="max-h-[90vh] overflow-y-auto sm:max-w-2xl"><DialogHeader><DialogTitle>{eventItem?"Edit event":"Add event"}</DialogTitle><DialogDescription>Schedule and publish a studio event. Internal notes are never included when sharing.</DialogDescription></DialogHeader><form onSubmit={submit} className="grid gap-4 sm:grid-cols-2">
 <div className="space-y-2 sm:col-span-2"><Label htmlFor="event-title">Title</Label><Input id="event-title" required value={form.title} onChange={e=>field("title",e.target.value)}/></div>
 <div className="space-y-2"><Label>Event type</Label><Select value={form.event_type} onValueChange={v=>v&&field("event_type",v)}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{EVENT_TYPES.map(v=><SelectItem key={v} value={v}>{v}</SelectItem>)}</SelectContent></Select></div>
 <div className="space-y-2"><Label>Status</Label><Select value={form.status} onValueChange={v=>v&&field("status",v)}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{EVENT_STATUSES.map(v=><SelectItem key={v} value={v}>{v}</SelectItem>)}</SelectContent></Select></div>
 <div className="space-y-2"><Label htmlFor="event-date">Date</Label><Input id="event-date" type="date" required value={form.event_date} onChange={e=>field("event_date",e.target.value)}/></div><div/>
 <div className="space-y-2"><Label htmlFor="event-start">Start time</Label><Input id="event-start" type="time" required value={form.start_time} onChange={e=>field("start_time",e.target.value)}/></div><div className="space-y-2"><Label htmlFor="event-end">End time</Label><Input id="event-end" type="time" required value={form.end_time} onChange={e=>field("end_time",e.target.value)}/></div>
 <div className="space-y-2 sm:col-span-2"><Label htmlFor="event-location">Location</Label><Input id="event-location" required value={form.location} onChange={e=>field("location",e.target.value)}/></div>
 <div className="space-y-2"><Label htmlFor="event-capacity">Capacity</Label><Input id="event-capacity" type="number" min={1} max={10000} required value={form.max_capacity} onChange={e=>field("max_capacity",Number(e.target.value))}/></div><div className="space-y-2"><Label htmlFor="event-fee">Fee (₹)</Label><Input id="event-fee" type="number" min={0} step="0.01" required value={form.fee} onChange={e=>field("fee",Number(e.target.value))}/></div>
 <div className="space-y-2 sm:col-span-2"><Label htmlFor="event-phone">Contact phone</Label><Input id="event-phone" inputMode="tel" value={form.contact_phone??""} onChange={e=>field("contact_phone",e.target.value)}/></div>
 <div className="space-y-2 sm:col-span-2"><Label htmlFor="event-description">Description</Label><Textarea id="event-description" value={form.description??""} onChange={e=>field("description",e.target.value)}/></div><div className="space-y-2 sm:col-span-2"><Label htmlFor="event-notes">Internal notes</Label><Textarea id="event-notes" value={form.notes??""} onChange={e=>field("notes",e.target.value)}/></div>
 {error&&<p role="alert" className="text-sm text-destructive sm:col-span-2">{error}</p>}<div className="flex justify-end gap-2 sm:col-span-2"><Button type="button" variant="outline" onClick={()=>close(false)}>Cancel</Button><Button type="submit" disabled={saving}>{saving&&<LoaderCircle className="animate-spin"/>}{eventItem?"Save changes":"Add event"}</Button></div>
 </form></DialogContent></Dialog>}
