import { supabase } from "@/lib/supabase";
export interface InstructorSession { id:number;class_id:number;session_date:string;assigned_instructor_id:number;substitute_instructor_id:number|null;status:string;rate:number;notes:string|null;Classes?:{class_name:string;start_time:string;end_time:string}|null;substitute?:{name:string}|null }
export interface InstructorPayment { id:number;instructor_id:number;period_start:string;period_end:string;amount:number;status:string;payment_method:string|null;reference_number:string|null;paid_at:string|null;notes:string|null }
export interface ClassOption {id:number;class_name:string;day:string;start_time:string;end_time:string;instructor_id:number|null}
const message=(error:unknown,fallback:string)=>error&&typeof error==="object"&&"message" in error?`${fallback} ${String(error.message)}`:fallback;
async function getData(instructorId:number){const [sessions,payments,classes,instructors]=await Promise.all([
 supabase.from("Instructor_Sessions").select("id,class_id,session_date,assigned_instructor_id,substitute_instructor_id,status,rate,notes,Classes(class_name,start_time,end_time),substitute:Instructors!Instructor_Sessions_substitute_instructor_id_fkey(name)").or(`assigned_instructor_id.eq.${instructorId},substitute_instructor_id.eq.${instructorId}`).order("session_date",{ascending:false}),
 supabase.from("Instructor_Payments").select("id,instructor_id,period_start,period_end,amount,status,payment_method,reference_number,paid_at,notes").eq("instructor_id",instructorId).order("period_start",{ascending:false}),
 supabase.from("Classes").select("id,class_name,day,start_time,end_time,instructor_id").eq("status","Active").order("class_name"),
 supabase.from("Instructors").select("id,name").eq("status","Active").order("name")]);
 for(const result of [sessions,payments,classes,instructors])if(result.error)throw new Error(message(result.error,"Unable to load instructor operations."));
 return{sessions:(sessions.data??[]).map(x=>({...x,rate:Number(x.rate)})) as unknown as InstructorSession[],payments:(payments.data??[]).map(x=>({...x,amount:Number(x.amount)})) as InstructorPayment[],classes:(classes.data??[]) as ClassOption[],instructors:(instructors.data??[]) as {id:number;name:string}[]};}
async function saveSession(input:{id?:number;classId:number;date:string;assignedId:number;substituteId:number|null;status:string;rate:number;notes:string}){const{error}=await supabase.rpc("save_instructor_session",{p_id:input.id??null,p_class_id:input.classId,p_session_date:input.date,p_assigned:input.assignedId,p_substitute:input.substituteId,p_status:input.status,p_rate:input.rate,p_notes:input.notes});if(error)throw new Error(message(error,"Unable to save instructor session."));}
async function createPayment(instructorId:number,input:{start:string;end:string;amount:number;notes:string}){const{error}=await supabase.from("Instructor_Payments").insert({instructor_id:instructorId,period_start:input.start,period_end:input.end,amount:input.amount,notes:input.notes.trim()||null});if(error)throw new Error(message(error,"Unable to add instructor payment."));}
async function markPaid(id:number,method:string,reference:string){const{error}=await supabase.from("Instructor_Payments").update({status:"Paid",payment_method:method.trim()||null,reference_number:reference.trim()||null,paid_at:new Date().toISOString(),updated_at:new Date().toISOString()}).eq("id",id);if(error)throw new Error(message(error,"Unable to mark instructor payment paid."));}
export const instructorOperationsService={getData,saveSession,createPayment,markPaid};
