[{
	"resource": "/c:/Users/Footloose Alley/Documents/footloose-alley-studio-manager-v2/app/(dashboard)/enquiries/page.tsx",
	"owner": "typescript",
	"code": "2300",
	"severity": 8,
	"message": "Duplicate identifier 'AlertCircle'.",
	"source": "ts",
	"startLineNumber": 4,
	"startColumn": 3,
	"endLineNumber": 4,
	"endColumn": 14,
	"modelVersionId": 4,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/Footloose Alley/Documents/footloose-alley-studio-manager-v2/app/(dashboard)/enquiries/page.tsx",
	"owner": "typescript",
	"code": "2300",
	"severity": 8,
	"message": "Duplicate identifier 'Loader2'.",
	"source": "ts",
	"startLineNumber": 5,
	"startColumn": 3,
	"endLineNumber": 5,
	"endColumn": 10,
	"modelVersionId": 4,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/Footloose Alley/Documents/footloose-alley-studio-manager-v2/app/(dashboard)/enquiries/page.tsx",
	"owner": "typescript",
	"code": "2300",
	"severity": 8,
	"message": "Duplicate identifier 'RefreshCw'.",
	"source": "ts",
	"startLineNumber": 6,
	"startColumn": 3,
	"endLineNumber": 6,
	"endColumn": 12,
	"modelVersionId": 4,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/Footloose Alley/Documents/footloose-alley-studio-manager-v2/app/(dashboard)/enquiries/page.tsx",
	"owner": "typescript",
	"code": "2300",
	"severity": 8,
	"message": "Duplicate identifier 'Trash2'.",
	"source": "ts",
	"startLineNumber": 7,
	"startColumn": 3,
	"endLineNumber": 7,
	"endColumn": 9,
	"modelVersionId": 4,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/Footloose Alley/Documents/footloose-alley-studio-manager-v2/app/(dashboard)/enquiries/page.tsx",
	"owner": "typescript",
	"code": "2300",
	"severity": 8,
	"message": "Duplicate identifier 'X'.",
	"source": "ts",
	"startLineNumber": 8,
	"startColumn": 3,
	"endLineNumber": 8,
	"endColumn": 4,
	"modelVersionId": 4,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/Footloose Alley/Documents/footloose-alley-studio-manager-v2/app/(dashboard)/enquiries/page.tsx",
	"owner": "typescript",
	"code": "2300",
	"severity": 8,
	"message": "Duplicate identifier 'useCallback'.",
	"source": "ts",
	"startLineNumber": 11,
	"startColumn": 3,
	"endLineNumber": 11,
	"endColumn": 14,
	"modelVersionId": 4,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/Footloose Alley/Documents/footloose-alley-studio-manager-v2/app/(dashboard)/enquiries/page.tsx",
	"owner": "typescript",
	"code": "2300",
	"severity": 8,
	"message": "Duplicate identifier 'useEffect'.",
	"source": "ts",
	"startLineNumber": 12,
	"startColumn": 3,
	"endLineNumber": 12,
	"endColumn": 12,
	"modelVersionId": 4,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/Footloose Alley/Documents/footloose-alley-studio-manager-v2/app/(dashboard)/enquiries/page.tsx",
	"owner": "typescript",
	"code": "2300",
	"severity": 8,
	"message": "Duplicate identifier 'useMemo'.",
	"source": "ts",
	"startLineNumber": 13,
	"startColumn": 3,
	"endLineNumber": 13,
	"endColumn": 10,
	"modelVersionId": 4,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/Footloose Alley/Documents/footloose-alley-studio-manager-v2/app/(dashboard)/enquiries/page.tsx",
	"owner": "typescript",
	"code": "2300",
	"severity": 8,
	"message": "Duplicate identifier 'useState'.",
	"source": "ts",
	"startLineNumber": 14,
	"startColumn": 3,
	"endLineNumber": 14,
	"endColumn": 11,
	"modelVersionId": 4,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/Footloose Alley/Documents/footloose-alley-studio-manager-v2/app/(dashboard)/enquiries/page.tsx",
	"owner": "typescript",
	"code": "2300",
	"severity": 8,
	"message": "Duplicate identifier 'EnquiryDashboard'.",
	"source": "ts",
	"startLineNumber": 17,
	"startColumn": 8,
	"endLineNumber": 17,
	"endColumn": 24,
	"modelVersionId": 4,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/Footloose Alley/Documents/footloose-alley-studio-manager-v2/app/(dashboard)/enquiries/page.tsx",
	"owner": "typescript",
	"code": "2300",
	"severity": 8,
	"message": "Duplicate identifier 'EnquiryFormDialog'.",
	"source": "ts",
	"startLineNumber": 18,
	"startColumn": 8,
	"endLineNumber": 18,
	"endColumn": 25,
	"modelVersionId": 4,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/Footloose Alley/Documents/footloose-alley-studio-manager-v2/app/(dashboard)/enquiries/page.tsx",
	"owner": "typescript",
	"code": "2300",
	"severity": 8,
	"message": "Duplicate identifier 'EnquiryTable'.",
	"source": "ts",
	"startLineNumber": 19,
	"startColumn": 8,
	"endLineNumber": 19,
	"endColumn": 20,
	"modelVersionId": 4,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/Footloose Alley/Documents/footloose-alley-studio-manager-v2/app/(dashboard)/enquiries/page.tsx",
	"owner": "typescript",
	"code": "2300",
	"severity": 8,
	"message": "Duplicate identifier 'enquiriesService'.",
	"source": "ts",
	"startLineNumber": 22,
	"startColumn": 3,
	"endLineNumber": 22,
	"endColumn": 19,
	"modelVersionId": 4,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/Footloose Alley/Documents/footloose-alley-studio-manager-v2/app/(dashboard)/enquiries/page.tsx",
	"owner": "typescript",
	"code": "2300",
	"severity": 8,
	"message": "Duplicate identifier 'Enquiry'.",
	"source": "ts",
	"startLineNumber": 23,
	"startColumn": 8,
	"endLineNumber": 23,
	"endColumn": 15,
	"modelVersionId": 4,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/Footloose Alley/Documents/footloose-alley-studio-manager-v2/app/(dashboard)/enquiries/page.tsx",
	"owner": "typescript",
	"code": "2300",
	"severity": 8,
	"message": "Duplicate identifier 'EnquiryFilters'.",
	"source": "ts",
	"startLineNumber": 24,
	"startColumn": 8,
	"endLineNumber": 24,
	"endColumn": 22,
	"modelVersionId": 4,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/Footloose Alley/Documents/footloose-alley-studio-manager-v2/app/(dashboard)/enquiries/page.tsx",
	"owner": "typescript",
	"code": "2300",
	"severity": 8,
	"message": "Duplicate identifier 'EnquiryStatus'.",
	"source": "ts",
	"startLineNumber": 25,
	"startColumn": 8,
	"endLineNumber": 25,
	"endColumn": 21,
	"modelVersionId": 4,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/Footloose Alley/Documents/footloose-alley-studio-manager-v2/app/(dashboard)/enquiries/page.tsx",
	"owner": "typescript",
	"code": "2451",
	"severity": 8,
	"message": "Cannot redeclare block-scoped variable 'DEFAULT_FILTERS'.",
	"source": "ts",
	"startLineNumber": 28,
	"startColumn": 7,
	"endLineNumber": 28,
	"endColumn": 22,
	"modelVersionId": 4,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/Footloose Alley/Documents/footloose-alley-studio-manager-v2/app/(dashboard)/enquiries/page.tsx",
	"owner": "typescript",
	"code": "2393",
	"severity": 8,
	"message": "Duplicate function implementation.",
	"source": "ts",
	"startLineNumber": 43,
	"startColumn": 10,
	"endLineNumber": 43,
	"endColumn": 29,
	"modelVersionId": 4,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/Footloose Alley/Documents/footloose-alley-studio-manager-v2/app/(dashboard)/enquiries/page.tsx",
	"owner": "typescript",
	"code": "2323",
	"severity": 8,
	"message": "Cannot redeclare exported variable 'default'.",
	"source": "ts",
	"startLineNumber": 188,
	"startColumn": 25,
	"endLineNumber": 188,
	"endColumn": 38,
	"modelVersionId": 4,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/Footloose Alley/Documents/footloose-alley-studio-manager-v2/app/(dashboard)/enquiries/page.tsx",
	"owner": "typescript",
	"code": "2393",
	"severity": 8,
	"message": "Duplicate function implementation.",
	"source": "ts",
	"startLineNumber": 188,
	"startColumn": 25,
	"endLineNumber": 188,
	"endColumn": 38,
	"modelVersionId": 4,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/Footloose Alley/Documents/footloose-alley-studio-manager-v2/app/(dashboard)/enquiries/page.tsx",
	"owner": "typescript",
	"code": "2300",
	"severity": 8,
	"message": "Duplicate identifier 'AlertCircle'.",
	"source": "ts",
	"startLineNumber": 567,
	"startColumn": 3,
	"endLineNumber": 567,
	"endColumn": 14,
	"modelVersionId": 4,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/Footloose Alley/Documents/footloose-alley-studio-manager-v2/app/(dashboard)/enquiries/page.tsx",
	"owner": "typescript",
	"code": "2300",
	"severity": 8,
	"message": "Duplicate identifier 'Loader2'.",
	"source": "ts",
	"startLineNumber": 568,
	"startColumn": 3,
	"endLineNumber": 568,
	"endColumn": 10,
	"modelVersionId": 4,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/Footloose Alley/Documents/footloose-alley-studio-manager-v2/app/(dashboard)/enquiries/page.tsx",
	"owner": "typescript",
	"code": "2300",
	"severity": 8,
	"message": "Duplicate identifier 'RefreshCw'.",
	"source": "ts",
	"startLineNumber": 569,
	"startColumn": 3,
	"endLineNumber": 569,
	"endColumn": 12,
	"modelVersionId": 4,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/Footloose Alley/Documents/footloose-alley-studio-manager-v2/app/(dashboard)/enquiries/page.tsx",
	"owner": "typescript",
	"code": "2300",
	"severity": 8,
	"message": "Duplicate identifier 'Trash2'.",
	"source": "ts",
	"startLineNumber": 570,
	"startColumn": 3,
	"endLineNumber": 570,
	"endColumn": 9,
	"modelVersionId": 4,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/Footloose Alley/Documents/footloose-alley-studio-manager-v2/app/(dashboard)/enquiries/page.tsx",
	"owner": "typescript",
	"code": "2300",
	"severity": 8,
	"message": "Duplicate identifier 'X'.",
	"source": "ts",
	"startLineNumber": 571,
	"startColumn": 3,
	"endLineNumber": 571,
	"endColumn": 4,
	"modelVersionId": 4,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/Footloose Alley/Documents/footloose-alley-studio-manager-v2/app/(dashboard)/enquiries/page.tsx",
	"owner": "typescript",
	"code": "2300",
	"severity": 8,
	"message": "Duplicate identifier 'useCallback'.",
	"source": "ts",
	"startLineNumber": 574,
	"startColumn": 3,
	"endLineNumber": 574,
	"endColumn": 14,
	"modelVersionId": 4,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/Footloose Alley/Documents/footloose-alley-studio-manager-v2/app/(dashboard)/enquiries/page.tsx",
	"owner": "typescript",
	"code": "2300",
	"severity": 8,
	"message": "Duplicate identifier 'useEffect'.",
	"source": "ts",
	"startLineNumber": 575,
	"startColumn": 3,
	"endLineNumber": 575,
	"endColumn": 12,
	"modelVersionId": 4,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/Footloose Alley/Documents/footloose-alley-studio-manager-v2/app/(dashboard)/enquiries/page.tsx",
	"owner": "typescript",
	"code": "2300",
	"severity": 8,
	"message": "Duplicate identifier 'useMemo'.",
	"source": "ts",
	"startLineNumber": 576,
	"startColumn": 3,
	"endLineNumber": 576,
	"endColumn": 10,
	"modelVersionId": 4,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/Footloose Alley/Documents/footloose-alley-studio-manager-v2/app/(dashboard)/enquiries/page.tsx",
	"owner": "typescript",
	"code": "2300",
	"severity": 8,
	"message": "Duplicate identifier 'useState'.",
	"source": "ts",
	"startLineNumber": 577,
	"startColumn": 3,
	"endLineNumber": 577,
	"endColumn": 11,
	"modelVersionId": 4,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/Footloose Alley/Documents/footloose-alley-studio-manager-v2/app/(dashboard)/enquiries/page.tsx",
	"owner": "typescript",
	"code": "2300",
	"severity": 8,
	"message": "Duplicate identifier 'EnquiryDashboard'.",
	"source": "ts",
	"startLineNumber": 581,
	"startColumn": 8,
	"endLineNumber": 581,
	"endColumn": 24,
	"modelVersionId": 4,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/Footloose Alley/Documents/footloose-alley-studio-manager-v2/app/(dashboard)/enquiries/page.tsx",
	"owner": "typescript",
	"code": "2300",
	"severity": 8,
	"message": "Duplicate identifier 'EnquiryFormDialog'.",
	"source": "ts",
	"startLineNumber": 582,
	"startColumn": 8,
	"endLineNumber": 582,
	"endColumn": 25,
	"modelVersionId": 4,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/Footloose Alley/Documents/footloose-alley-studio-manager-v2/app/(dashboard)/enquiries/page.tsx",
	"owner": "typescript",
	"code": "2300",
	"severity": 8,
	"message": "Duplicate identifier 'EnquiryTable'.",
	"source": "ts",
	"startLineNumber": 583,
	"startColumn": 8,
	"endLineNumber": 583,
	"endColumn": 20,
	"modelVersionId": 4,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/Footloose Alley/Documents/footloose-alley-studio-manager-v2/app/(dashboard)/enquiries/page.tsx",
	"owner": "typescript",
	"code": "2300",
	"severity": 8,
	"message": "Duplicate identifier 'enquiriesService'.",
	"source": "ts",
	"startLineNumber": 590,
	"startColumn": 3,
	"endLineNumber": 590,
	"endColumn": 19,
	"modelVersionId": 4,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/Footloose Alley/Documents/footloose-alley-studio-manager-v2/app/(dashboard)/enquiries/page.tsx",
	"owner": "typescript",
	"code": "2300",
	"severity": 8,
	"message": "Duplicate identifier 'Enquiry'.",
	"source": "ts",
	"startLineNumber": 591,
	"startColumn": 8,
	"endLineNumber": 591,
	"endColumn": 15,
	"modelVersionId": 4,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/Footloose Alley/Documents/footloose-alley-studio-manager-v2/app/(dashboard)/enquiries/page.tsx",
	"owner": "typescript",
	"code": "2300",
	"severity": 8,
	"message": "Duplicate identifier 'EnquiryFilters'.",
	"source": "ts",
	"startLineNumber": 592,
	"startColumn": 8,
	"endLineNumber": 592,
	"endColumn": 22,
	"modelVersionId": 4,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/Footloose Alley/Documents/footloose-alley-studio-manager-v2/app/(dashboard)/enquiries/page.tsx",
	"owner": "typescript",
	"code": "2300",
	"severity": 8,
	"message": "Duplicate identifier 'EnquiryStatus'.",
	"source": "ts",
	"startLineNumber": 593,
	"startColumn": 8,
	"endLineNumber": 593,
	"endColumn": 21,
	"modelVersionId": 4,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/Footloose Alley/Documents/footloose-alley-studio-manager-v2/app/(dashboard)/enquiries/page.tsx",
	"owner": "typescript",
	"code": "2451",
	"severity": 8,
	"message": "Cannot redeclare block-scoped variable 'DEFAULT_FILTERS'.",
	"source": "ts",
	"startLineNumber": 596,
	"startColumn": 7,
	"endLineNumber": 596,
	"endColumn": 22,
	"modelVersionId": 4,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/Footloose Alley/Documents/footloose-alley-studio-manager-v2/app/(dashboard)/enquiries/page.tsx",
	"owner": "typescript",
	"code": "2393",
	"severity": 8,
	"message": "Duplicate function implementation.",
	"source": "ts",
	"startLineNumber": 611,
	"startColumn": 10,
	"endLineNumber": 611,
	"endColumn": 29,
	"modelVersionId": 4,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/Footloose Alley/Documents/footloose-alley-studio-manager-v2/app/(dashboard)/enquiries/page.tsx",
	"owner": "typescript",
	"code": "2323",
	"severity": 8,
	"message": "Cannot redeclare exported variable 'default'.",
	"source": "ts",
	"startLineNumber": 782,
	"startColumn": 25,
	"endLineNumber": 782,
	"endColumn": 38,
	"modelVersionId": 4,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/Footloose Alley/Documents/footloose-alley-studio-manager-v2/app/(dashboard)/enquiries/page.tsx",
	"owner": "typescript",
	"code": "2393",
	"severity": 8,
	"message": "Duplicate function implementation.",
	"source": "ts",
	"startLineNumber": 782,
	"startColumn": 25,
	"endLineNumber": 782,
	"endColumn": 38,
	"modelVersionId": 4,
	"origin": "extHost1"
}]