-- Footloose Alley Studio Manager v5.7.0 security audit and query indexes.
begin;

create table if not exists public.studio_audit_log (
  id bigint generated by default as identity primary key,
  table_name text not null,
  record_id text,
  action text not null check (action in ('INSERT','UPDATE','DELETE')),
  changed_by uuid references auth.users(id) on delete set null,
  changed_at timestamptz not null default now(),
  old_data jsonb,
  new_data jsonb
);
create index if not exists studio_audit_log_changed_at_idx on public.studio_audit_log(changed_at desc);
create index if not exists studio_audit_log_record_idx on public.studio_audit_log(table_name,record_id,changed_at desc);
alter table public.studio_audit_log enable row level security;
revoke all on public.studio_audit_log from public,anon,authenticated;
revoke all on sequence public.studio_audit_log_id_seq from public,anon,authenticated;
drop policy if exists studio_audit_log_admin_select on public.studio_audit_log;
create policy studio_audit_log_admin_select on public.studio_audit_log for select to authenticated
  using (public.current_app_role() = 'admin');
grant select on public.studio_audit_log to authenticated;

create or replace function public.capture_studio_audit()
returns trigger language plpgsql security definer set search_path=public,pg_temp as $$
declare old_row jsonb; new_row jsonb; audit_record_id text;
begin
  old_row := case when tg_op in ('UPDATE','DELETE') then to_jsonb(old) else null end;
  new_row := case when tg_op in ('INSERT','UPDATE') then to_jsonb(new) else null end;
  audit_record_id := coalesce(new_row->>'id',old_row->>'id');
  insert into public.studio_audit_log(table_name,record_id,action,changed_by,old_data,new_data)
  values(tg_table_name,audit_record_id,tg_op,auth.uid(),old_row,new_row);
  if tg_op = 'DELETE' then return old; end if;
  return new;
end $$;
revoke all on function public.capture_studio_audit() from public,anon,authenticated;

do $$
declare table_name text;
begin
  foreach table_name in array array[
    'Students','Enquiries','Payments','Events','Event_Registrations','Event_Refunds',
    'Event_Expenses','Instructors','Instructor_Sessions','Instructor_Payments',
    'Studio_Expenses','Cash_Reconciliations'
  ] loop
    if to_regclass(format('public.%I',table_name)) is not null then
      execute format('drop trigger if exists studio_audit_trigger on public.%I',table_name);
      execute format('create trigger studio_audit_trigger after insert or update or delete on public.%I for each row execute function public.capture_studio_audit()',table_name);
    end if;
  end loop;
end $$;

create index if not exists enquiries_created_at_idx on public."Enquiries"(created_at desc);
create index if not exists enquiries_status_follow_up_idx on public."Enquiries"("Status","Follow_up_date");
create index if not exists enquiries_trial_date_idx on public."Enquiries"(trial_date) where trial_date is not null;
create index if not exists payments_date_status_idx on public."Payments"(payment_date desc,payment_status);
create index if not exists event_registrations_event_status_idx on public."Event_Registrations"(event_id,payment_status,attendance_status);
create index if not exists event_expenses_date_idx on public."Event_Expenses"(expense_date desc);
create index if not exists instructor_payments_status_paid_idx on public."Instructor_Payments"(status,paid_at desc);
create index if not exists cash_reconciliations_date_idx on public."Cash_Reconciliations"(reconciliation_date desc);

commit;
