-- Footloose Alley Studio Manager v5.2.0 public class bookings and waitlists.

begin;

alter table public."Classes"
  add column if not exists public_booking_enabled boolean not null default false;

create table if not exists public."Class_Bookings" (
  id bigint generated by default as identity primary key,
  class_id bigint not null references public."Classes" (id) on delete restrict,
  class_date date not null,
  participant_name text not null,
  phone text not null,
  email text,
  status text not null,
  access_token uuid not null default gen_random_uuid() unique,
  booking_source text not null default 'Public Link',
  cancelled_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint class_bookings_status_check check (status in ('Booked','Waitlisted','Cancelled')),
  constraint class_bookings_name_check check (length(trim(participant_name)) between 2 and 120),
  constraint class_bookings_phone_check check (length(phone) between 7 and 15),
  constraint class_bookings_unique_phone unique (class_id, class_date, phone)
);

create index if not exists class_bookings_session_idx on public."Class_Bookings" (class_id, class_date, status, created_at);
alter table public."Class_Bookings" enable row level security;
drop policy if exists class_bookings_staff_select on public."Class_Bookings";
create policy class_bookings_staff_select on public."Class_Bookings" for select to authenticated using (public.current_app_role() in ('admin','receptionist'));
drop policy if exists class_bookings_staff_update on public."Class_Bookings";
create policy class_bookings_staff_update on public."Class_Bookings" for update to authenticated using (public.current_app_role() in ('admin','receptionist')) with check (public.current_app_role() in ('admin','receptionist'));
grant select, update on public."Class_Bookings" to authenticated;

create or replace function public.create_public_class_booking(p_class_id bigint, p_class_date date, p_name text, p_phone text, p_email text default null)
returns public."Class_Bookings"
language plpgsql security definer set search_path=public
as $$
declare class_record public."Classes"; booked_count integer; result public."Class_Bookings";
begin
  select * into class_record from public."Classes" where id=p_class_id for update;
  if class_record.id is null or class_record.status <> 'Active' or not class_record.public_booking_enabled then raise exception 'This class is not accepting online bookings.'; end if;
  if extract(isodow from p_class_date) <> case class_record.day when 'Monday' then 1 when 'Tuesday' then 2 when 'Wednesday' then 3 when 'Thursday' then 4 when 'Friday' then 5 when 'Saturday' then 6 when 'Sunday' then 7 end then raise exception 'Choose a valid class date.'; end if;
  if p_class_date < current_date or p_class_date > current_date + 30 then raise exception 'Bookings are available for the next 30 days.'; end if;
  select count(*) into booked_count from public."Class_Bookings" where class_id=p_class_id and class_date=p_class_date and status='Booked';
  insert into public."Class_Bookings" (class_id,class_date,participant_name,phone,email,status)
    values (p_class_id,p_class_date,trim(p_name),p_phone,nullif(lower(trim(coalesce(p_email,''))),''),case when booked_count < class_record.max_capacity then 'Booked' else 'Waitlisted' end)
    returning * into result;
  return result;
end;
$$;

create or replace function public.cancel_public_class_booking(p_access_token uuid)
returns public."Class_Bookings"
language plpgsql security definer set search_path=public
as $$
declare cancelled public."Class_Bookings"; prior_status text; promoted_id bigint;
begin
  select status into prior_status from public."Class_Bookings" where access_token=p_access_token and status in ('Booked','Waitlisted') for update;
  update public."Class_Bookings" set status='Cancelled',cancelled_at=now(),updated_at=now()
    where access_token=p_access_token and status in ('Booked','Waitlisted') returning * into cancelled;
  if cancelled.id is null then raise exception 'This booking is unavailable or already cancelled.'; end if;
  if prior_status='Booked' then
    select id into promoted_id from public."Class_Bookings" where class_id=cancelled.class_id and class_date=cancelled.class_date and status='Waitlisted' order by created_at,id limit 1 for update skip locked;
    if promoted_id is not null then update public."Class_Bookings" set status='Booked',updated_at=now() where id=promoted_id; end if;
  end if;
  return cancelled;
end;
$$;

revoke all on function public.create_public_class_booking(bigint,date,text,text,text) from public,anon,authenticated;
revoke all on function public.cancel_public_class_booking(uuid) from public,anon,authenticated;
grant execute on function public.create_public_class_booking(bigint,date,text,text,text) to service_role;
grant execute on function public.cancel_public_class_booking(uuid) to service_role;

commit;
