-- Footloose Alley Studio Manager v5.1.0 event expenses and profitability.

begin;

create table if not exists public."Event_Expenses" (
  id bigint generated by default as identity primary key,
  event_id bigint not null references public."Events" (id) on delete cascade,
  category text not null,
  description text not null,
  amount numeric(10,2) not null,
  expense_date date not null default current_date,
  payment_method text,
  reference_number text,
  created_by uuid references auth.users (id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint event_expenses_amount_check check (amount > 0),
  constraint event_expenses_category_check check (length(trim(category)) between 2 and 50),
  constraint event_expenses_description_check check (length(trim(description)) between 2 and 200)
);

create index if not exists event_expenses_event_date_idx
  on public."Event_Expenses" (event_id, expense_date desc);

alter table public."Event_Expenses" enable row level security;

drop policy if exists event_expenses_select_staff on public."Event_Expenses";
create policy event_expenses_select_staff on public."Event_Expenses"
  for select to authenticated
  using (public.current_app_role() in ('admin','receptionist'));

drop policy if exists event_expenses_insert_staff on public."Event_Expenses";
create policy event_expenses_insert_staff on public."Event_Expenses"
  for insert to authenticated
  with check (public.current_app_role() in ('admin','receptionist'));

drop policy if exists event_expenses_update_staff on public."Event_Expenses";
create policy event_expenses_update_staff on public."Event_Expenses"
  for update to authenticated
  using (public.current_app_role() in ('admin','receptionist'))
  with check (public.current_app_role() in ('admin','receptionist'));

drop policy if exists event_expenses_delete_staff on public."Event_Expenses";
create policy event_expenses_delete_staff on public."Event_Expenses"
  for delete to authenticated
  using (public.current_app_role() in ('admin','receptionist'));

grant select, insert, update, delete on public."Event_Expenses" to authenticated;

commit;
