begin;

create table if not exists public."Event_Registrations" (
  id bigint generated by default as identity primary key,
  event_id bigint not null references public."Events" (id) on delete cascade,
  participant_name text not null,
  phone text not null,
  payment_status text not null default 'Pending',
  amount_paid numeric(10,2) not null default 0,
  attendance_status text not null default 'Registered',
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint event_registrations_name_check check (length(trim(participant_name)) between 2 and 120),
  constraint event_registrations_phone_check check (phone ~ '^[0-9]{7,15}$'),
  constraint event_registrations_payment_status_check check (payment_status in ('Pending','Paid','Waived','Refunded')),
  constraint event_registrations_amount_check check (amount_paid >= 0),
  constraint event_registrations_attendance_status_check check (attendance_status in ('Registered','Attended','No Show','Cancelled')),
  constraint event_registrations_event_phone_unique unique (event_id, phone)
);

create index if not exists event_registrations_event_id_idx
  on public."Event_Registrations" (event_id);

create index if not exists event_registrations_event_payment_idx
  on public."Event_Registrations" (event_id, payment_status);

create index if not exists event_registrations_event_attendance_idx
  on public."Event_Registrations" (event_id, attendance_status);

alter table public."Event_Registrations" enable row level security;

drop policy if exists event_registrations_select_staff on public."Event_Registrations";
create policy event_registrations_select_staff
  on public."Event_Registrations" for select to authenticated
  using (public.current_app_role() in ('admin', 'receptionist'));

drop policy if exists event_registrations_insert_staff on public."Event_Registrations";
create policy event_registrations_insert_staff
  on public."Event_Registrations" for insert to authenticated
  with check (public.current_app_role() in ('admin', 'receptionist'));

drop policy if exists event_registrations_update_staff on public."Event_Registrations";
create policy event_registrations_update_staff
  on public."Event_Registrations" for update to authenticated
  using (public.current_app_role() in ('admin', 'receptionist'))
  with check (public.current_app_role() in ('admin', 'receptionist'));

drop policy if exists event_registrations_delete_admin on public."Event_Registrations";
create policy event_registrations_delete_admin
  on public."Event_Registrations" for delete to authenticated
  using (public.current_app_role() = 'admin');

grant select, insert, update, delete on table public."Event_Registrations" to authenticated;
grant usage, select on sequence public."Event_Registrations_id_seq" to authenticated;

commit;
