begin;

create table if not exists public.push_subscriptions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users (id) on delete cascade,
  endpoint text not null unique,
  p256dh text not null,
  auth text not null,
  user_agent text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint push_subscriptions_endpoint_https_check
    check (endpoint like 'https://%'),
  constraint push_subscriptions_p256dh_not_empty_check
    check (length(trim(p256dh)) > 0),
  constraint push_subscriptions_auth_not_empty_check
    check (length(trim(auth)) > 0)
);

create index if not exists push_subscriptions_user_id_idx
  on public.push_subscriptions (user_id);

alter table public.push_subscriptions enable row level security;

revoke all on table public.push_subscriptions from anon;
revoke all on table public.push_subscriptions from authenticated;
revoke all on sequence public.push_subscriptions_id_seq from anon;
revoke all on sequence public.push_subscriptions_id_seq from authenticated;

create table if not exists public.staff_push_events (
  id bigint generated by default as identity primary key,
  event_type text not null,
  entity_id bigint,
  title text not null,
  body text not null,
  href text not null,
  dedupe_key text not null unique,
  created_at timestamptz not null default now(),
  delivered_at timestamptz,
  constraint staff_push_events_type_check
    check (event_type in ('enquiry', 'trial', 'overdue_follow_up')),
  constraint staff_push_events_title_not_empty_check
    check (length(trim(title)) between 1 and 120),
  constraint staff_push_events_body_not_empty_check
    check (length(trim(body)) between 1 and 240),
  constraint staff_push_events_href_path_check
    check (href like '/%'),
  constraint staff_push_events_dedupe_key_not_empty_check
    check (length(trim(dedupe_key)) between 1 and 200)
);

create index if not exists staff_push_events_pending_idx
  on public.staff_push_events (created_at)
  where delivered_at is null;

alter table public.staff_push_events enable row level security;

revoke all on table public.staff_push_events from anon;
revoke all on table public.staff_push_events from authenticated;
revoke all on sequence public.staff_push_events_id_seq from anon;
revoke all on sequence public.staff_push_events_id_seq from authenticated;

create or replace function public.enqueue_new_enquiry_push()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  insert into public.staff_push_events (
    event_type,
    entity_id,
    title,
    body,
    href,
    dedupe_key
  )
  values (
    'enquiry',
    new.id,
    'New enquiry',
    'A new enquiry needs your attention.',
    '/enquiries',
    'enquiry:' || new.id::text
  )
  on conflict (dedupe_key) do nothing;

  return new;
end;
$$;

drop trigger if exists enqueue_new_enquiry_push_trigger
  on public."Enquiries";

create trigger enqueue_new_enquiry_push_trigger
after insert on public."Enquiries"
for each row
execute function public.enqueue_new_enquiry_push();

create or replace function public.enqueue_trial_push()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  if new.trial_date is null then
    return new;
  end if;

  if tg_op = 'UPDATE' and new.trial_date is not distinct from old.trial_date then
    return new;
  end if;

  insert into public.staff_push_events (
    event_type,
    entity_id,
    title,
    body,
    href,
    dedupe_key
  )
  values (
    'trial',
    new.id,
    'Trial request',
    'A trial request needs your attention.',
    '/trials',
    'trial:' || new.id::text || ':' || new.trial_date::text
  )
  on conflict (dedupe_key) do nothing;

  return new;
end;
$$;

drop trigger if exists enqueue_trial_push_trigger
  on public."Enquiries";

create trigger enqueue_trial_push_trigger
after insert or update of trial_date on public."Enquiries"
for each row
execute function public.enqueue_trial_push();

commit;
