-- Footloose Alley Studio Manager v5.0.0 event cancellations and refunds.

begin;

alter table public."Event_Registrations"
  add column if not exists cancelled_at timestamptz,
  add column if not exists cancelled_by uuid references auth.users (id) on delete set null,
  add column if not exists cancellation_reason text;

create sequence if not exists public.event_refund_number_seq start with 1 increment by 1;
revoke all on sequence public.event_refund_number_seq from anon;
grant usage, select on sequence public.event_refund_number_seq to authenticated, service_role;

create table if not exists public."Event_Refunds" (
  id bigint generated by default as identity primary key,
  registration_id bigint not null references public."Event_Registrations" (id) on delete restrict,
  event_id bigint not null references public."Events" (id) on delete restrict,
  refund_number text not null unique,
  amount numeric(10,2) not null,
  reason text not null,
  reference_number text,
  created_by uuid references auth.users (id) on delete set null,
  created_at timestamptz not null default now(),
  constraint event_refunds_amount_check check (amount > 0),
  constraint event_refunds_reason_check check (length(trim(reason)) between 3 and 300)
);

create index if not exists event_refunds_registration_idx on public."Event_Refunds" (registration_id);
create index if not exists event_refunds_event_created_idx on public."Event_Refunds" (event_id, created_at);
alter table public."Event_Refunds" enable row level security;
drop policy if exists event_refunds_select_staff on public."Event_Refunds";
create policy event_refunds_select_staff on public."Event_Refunds" for select to authenticated using (public.current_app_role() in ('admin','receptionist'));
drop policy if exists event_refunds_insert_staff on public."Event_Refunds";
create policy event_refunds_insert_staff on public."Event_Refunds" for insert to authenticated with check (public.current_app_role() in ('admin','receptionist'));
grant select, insert on public."Event_Refunds" to authenticated;

create or replace function public.cancel_event_registration(p_registration_id bigint, p_reason text)
returns public."Event_Registrations"
language plpgsql security invoker set search_path = public
as $$
declare updated_registration public."Event_Registrations";
begin
  if public.current_app_role() not in ('admin','receptionist') then raise exception 'Staff access is required.' using errcode = '42501'; end if;
  if length(trim(coalesce(p_reason,''))) < 3 then raise exception 'Enter a cancellation reason.'; end if;
  update public."Event_Registrations" set attendance_status='Cancelled', cancelled_at=now(), cancelled_by=auth.uid(), cancellation_reason=trim(p_reason), updated_at=now()
    where id=p_registration_id and attendance_status <> 'Cancelled' returning * into updated_registration;
  if updated_registration.id is null then raise exception 'An active registration is required.' using errcode='P0002'; end if;
  update public."Event_Attendees" set attendance_status='Cancelled', checked_in_at=null, updated_at=now() where registration_id=p_registration_id;
  return updated_registration;
end;
$$;

create or replace function public.refund_event_registration(p_registration_id bigint, p_amount numeric, p_reason text, p_reference text default null, p_cancel boolean default true)
returns public."Event_Registrations"
language plpgsql security invoker set search_path = public
as $$
declare registration public."Event_Registrations"; already_refunded numeric; updated_registration public."Event_Registrations";
begin
  if public.current_app_role() not in ('admin','receptionist') then raise exception 'Staff access is required.' using errcode='42501'; end if;
  if p_amount is null or p_amount <= 0 then raise exception 'Refund amount must be greater than zero.'; end if;
  if length(trim(coalesce(p_reason,''))) < 3 then raise exception 'Enter a refund reason.'; end if;
  select * into registration from public."Event_Registrations" where id=p_registration_id for update;
  if registration.id is null or registration.payment_status not in ('Paid','Refunded') then raise exception 'A paid registration is required.' using errcode='P0002'; end if;
  select coalesce(sum(amount),0) into already_refunded from public."Event_Refunds" where registration_id=p_registration_id;
  if p_amount > registration.amount_paid - already_refunded then raise exception 'Refund exceeds the remaining refundable amount.'; end if;
  insert into public."Event_Refunds" (registration_id,event_id,refund_number,amount,reason,reference_number,created_by)
    values (registration.id,registration.event_id,'FA-RFD-'||lpad(nextval('public.event_refund_number_seq')::text,6,'0'),round(p_amount,2),trim(p_reason),nullif(trim(coalesce(p_reference,'')),''),auth.uid());
  update public."Event_Registrations" set payment_status=case when already_refunded+p_amount >= amount_paid then 'Refunded' else 'Paid' end,
    attendance_status=case when p_cancel then 'Cancelled' else attendance_status end,
    cancelled_at=case when p_cancel then coalesce(cancelled_at,now()) else cancelled_at end,
    cancelled_by=case when p_cancel then coalesce(cancelled_by,auth.uid()) else cancelled_by end,
    cancellation_reason=case when p_cancel then coalesce(cancellation_reason,trim(p_reason)) else cancellation_reason end,
    updated_at=now() where id=p_registration_id returning * into updated_registration;
  if p_cancel then update public."Event_Attendees" set attendance_status='Cancelled',checked_in_at=null,updated_at=now() where registration_id=p_registration_id; end if;
  return updated_registration;
end;
$$;

revoke all on function public.cancel_event_registration(bigint,text) from public,anon;
revoke all on function public.refund_event_registration(bigint,numeric,text,text,boolean) from public,anon;
grant execute on function public.cancel_event_registration(bigint,text) to authenticated;
grant execute on function public.refund_event_registration(bigint,numeric,text,text,boolean) to authenticated;

commit;
