-- Footloose Alley Studio Manager v4.9.0 individual event attendee check-in.

begin;

create table if not exists public."Event_Attendees" (
  id bigint generated by default as identity primary key,
  registration_id bigint not null references public."Event_Registrations" (id) on delete cascade,
  event_id bigint not null references public."Events" (id) on delete cascade,
  position integer not null,
  participant_name text not null,
  is_primary boolean not null default false,
  attendance_status text not null default 'Registered',
  checked_in_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint event_attendees_position_check check (position between 1 and 20),
  constraint event_attendees_name_check check (length(trim(participant_name)) between 2 and 120),
  constraint event_attendees_status_check check (attendance_status in ('Registered','Attended','No Show','Cancelled')),
  constraint event_attendees_registration_position_unique unique (registration_id, position)
);

create index if not exists event_attendees_event_status_idx on public."Event_Attendees" (event_id, attendance_status);

create or replace function public.sync_event_registration_attendees()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  attendee_position integer;
  attendee_name text;
begin
  for attendee_position in 1..new.group_size loop
    attendee_name := case
      when attendee_position = 1 then new.participant_name
      else new.additional_participant_names[attendee_position - 1]
    end;
    insert into public."Event_Attendees" (registration_id, event_id, position, participant_name, is_primary)
    values (new.id, new.event_id, attendee_position, attendee_name, attendee_position = 1)
    on conflict (registration_id, position) do update
      set event_id = excluded.event_id,
          participant_name = excluded.participant_name,
          is_primary = excluded.is_primary,
          updated_at = now();
  end loop;
  delete from public."Event_Attendees"
    where registration_id = new.id and position > new.group_size;
  return new;
end;
$$;

drop trigger if exists sync_event_registration_attendees_trigger on public."Event_Registrations";
create trigger sync_event_registration_attendees_trigger
after insert or update of participant_name, additional_participant_names, group_size, event_id
on public."Event_Registrations"
for each row execute function public.sync_event_registration_attendees();

insert into public."Event_Attendees" (registration_id, event_id, position, participant_name, is_primary)
select registration.id, registration.event_id, positions.position,
  case when positions.position = 1 then registration.participant_name else registration.additional_participant_names[positions.position - 1] end,
  positions.position = 1
from public."Event_Registrations" registration
cross join lateral generate_series(1, registration.group_size) positions(position)
on conflict (registration_id, position) do update
  set participant_name = excluded.participant_name,
      event_id = excluded.event_id,
      is_primary = excluded.is_primary,
      updated_at = now();

alter table public."Event_Attendees" enable row level security;
drop policy if exists event_attendees_select_staff on public."Event_Attendees";
create policy event_attendees_select_staff on public."Event_Attendees" for select to authenticated
  using (public.current_app_role() in ('admin', 'receptionist'));
drop policy if exists event_attendees_update_staff on public."Event_Attendees";
create policy event_attendees_update_staff on public."Event_Attendees" for update to authenticated
  using (public.current_app_role() in ('admin', 'receptionist')) with check (public.current_app_role() in ('admin', 'receptionist'));

grant select, update on table public."Event_Attendees" to authenticated;

commit;
