-- Footloose Alley Studio Manager v4.7.2 event discount coupons.

begin;

create table if not exists public."Event_Coupons" (
  id bigint generated by default as identity primary key,
  event_id bigint not null references public."Events" (id) on delete cascade,
  code text not null,
  discount_percent numeric(5,2) not null,
  expires_at timestamptz,
  usage_limit integer,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint event_coupons_code_check check (code ~ '^[A-Z0-9_-]{3,24}$'),
  constraint event_coupons_discount_check check (discount_percent > 0 and discount_percent <= 100),
  constraint event_coupons_usage_limit_check check (usage_limit is null or usage_limit > 0),
  constraint event_coupons_event_code_unique unique (event_id, code)
);

alter table public."Event_Registrations"
  add column if not exists coupon_code text,
  add column if not exists original_amount numeric(10,2),
  add column if not exists discount_amount numeric(10,2) not null default 0,
  add column if not exists amount_due numeric(10,2);

alter table public."Event_Registrations" drop constraint if exists event_registrations_discount_amount_check;
alter table public."Event_Registrations" add constraint event_registrations_discount_amount_check check (discount_amount >= 0);
alter table public."Event_Registrations" drop constraint if exists event_registrations_amount_due_check;
alter table public."Event_Registrations" add constraint event_registrations_amount_due_check check (amount_due is null or amount_due >= 0);

create index if not exists event_coupons_event_id_idx on public."Event_Coupons" (event_id);
alter table public."Event_Coupons" enable row level security;

drop policy if exists event_coupons_select_staff on public."Event_Coupons";
create policy event_coupons_select_staff on public."Event_Coupons" for select to authenticated
  using (public.current_app_role() in ('admin', 'receptionist'));
drop policy if exists event_coupons_insert_staff on public."Event_Coupons";
create policy event_coupons_insert_staff on public."Event_Coupons" for insert to authenticated
  with check (public.current_app_role() in ('admin', 'receptionist'));
drop policy if exists event_coupons_update_staff on public."Event_Coupons";
create policy event_coupons_update_staff on public."Event_Coupons" for update to authenticated
  using (public.current_app_role() in ('admin', 'receptionist')) with check (public.current_app_role() in ('admin', 'receptionist'));
drop policy if exists event_coupons_delete_staff on public."Event_Coupons";
create policy event_coupons_delete_staff on public."Event_Coupons" for delete to authenticated
  using (public.current_app_role() in ('admin', 'receptionist'));

grant select, insert, update, delete on table public."Event_Coupons" to authenticated;
grant usage, select on sequence public."Event_Coupons_id_seq" to authenticated;

commit;
