begin;

alter table public."Enquiries"
  add column if not exists google_form_response_id text,
  add column if not exists intake_channel text;

create unique index if not exists enquiries_google_form_response_id_uidx
  on public."Enquiries" (google_form_response_id)
  where google_form_response_id is not null;

create table if not exists public."Student_Intake_Submissions" (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  google_form_response_id text not null,
  source text not null default 'Google Form',
  status text not null default 'Pending',
  "Name" text not null,
  "Phone" text not null,
  normalized_phone text not null,
  "Email" text,
  "Program" text,
  date_of_birth date,
  gender text,
  "Address" text,
  "Emergency_contact" text,
  photo_path text,
  medical_notes text,
  batch text,
  whatsapp_enabled boolean not null default true,
  notes text,
  reviewed_at timestamptz,
  reviewed_by uuid references auth.users (id) on delete set null,
  rejection_reason text,
  student_id bigint references public."Students" (id) on delete set null,
  constraint student_intake_google_response_unique
    unique (google_form_response_id),
  constraint student_intake_status_check
    check (status in ('Pending', 'Approved', 'Rejected')),
  constraint student_intake_name_not_empty
    check (length(trim("Name")) > 0),
  constraint student_intake_phone_not_empty
    check (length(trim("Phone")) > 0),
  constraint student_intake_normalized_phone_not_empty
    check (length(trim(normalized_phone)) > 0),
  constraint student_intake_gender_check
    check (
      gender is null
      or gender in ('Male', 'Female', 'Other', 'Prefer not to say')
    )
);

create index if not exists student_intake_status_created_idx
  on public."Student_Intake_Submissions" (status, created_at desc);

create index if not exists student_intake_normalized_phone_idx
  on public."Student_Intake_Submissions" (normalized_phone);

alter table public."Student_Intake_Submissions" enable row level security;

drop policy if exists student_intake_select_staff
  on public."Student_Intake_Submissions";
create policy student_intake_select_staff
  on public."Student_Intake_Submissions"
  for select
  to authenticated
  using (public.current_app_role() in ('admin', 'receptionist'));

drop policy if exists student_intake_update_staff
  on public."Student_Intake_Submissions";
create policy student_intake_update_staff
  on public."Student_Intake_Submissions"
  for update
  to authenticated
  using (public.current_app_role() in ('admin', 'receptionist'))
  with check (public.current_app_role() in ('admin', 'receptionist'));

grant select, update on table public."Student_Intake_Submissions"
  to authenticated;
grant usage, select on sequence public."Student_Intake_Submissions_id_seq"
  to authenticated;

create or replace function public.normalize_intake_phone(phone_value text)
returns text
language plpgsql
immutable
strict
set search_path = public
as $$
declare
  digits text := regexp_replace(phone_value, '[^0-9]', '', 'g');
begin
  if length(digits) = 12 and digits like '91%' then
    return right(digits, 10);
  end if;

  if length(digits) = 11 and digits like '0%' then
    return right(digits, 10);
  end if;

  return digits;
end;
$$;

revoke all on function public.normalize_intake_phone(text) from public;
grant execute on function public.normalize_intake_phone(text)
  to authenticated, service_role;

create or replace function public.approve_student_intake(submission_id bigint)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  submission public."Student_Intake_Submissions"%rowtype;
  created_student_id bigint;
begin
  if public.current_app_role() not in ('admin', 'receptionist') then
    raise exception 'Only active studio staff can approve registrations.';
  end if;

  select *
  into submission
  from public."Student_Intake_Submissions"
  where id = submission_id
  for update;

  if not found then
    raise exception 'Registration not found.';
  end if;

  if submission.status = 'Approved' and submission.student_id is not null then
    return submission.student_id;
  end if;

  if submission.status <> 'Pending' then
    raise exception 'Only pending registrations can be approved.';
  end if;

  if exists (
    select 1
    from public."Students"
    where public.normalize_intake_phone(coalesce("Phone", '')) =
      submission.normalized_phone
  ) then
    raise exception 'A student with this phone number already exists.';
  end if;

  insert into public."Students" (
    "Name",
    "Phone",
    "Email",
    "Program",
    "Fees",
    "Fees_due",
    "Status",
    "Address",
    "Emergency_contact",
    photo_url,
    join_date,
    date_of_birth,
    gender,
    fee_status,
    batch,
    medical_notes,
    attendance_percentage,
    whatsapp_enabled,
    notes,
    referred_by,
    membership_frozen
  )
  values (
    submission."Name",
    submission."Phone",
    submission."Email",
    submission."Program",
    0,
    0,
    'Inactive',
    submission."Address",
    submission."Emergency_contact",
    submission.photo_path,
    current_date,
    submission.date_of_birth,
    submission.gender,
    'Pending',
    submission.batch,
    submission.medical_notes,
    0,
    submission.whatsapp_enabled,
    submission.notes,
    'Google Student Registration Form',
    false
  )
  returning id into created_student_id;

  update public."Student_Intake_Submissions"
  set
    status = 'Approved',
    student_id = created_student_id,
    reviewed_at = now(),
    reviewed_by = auth.uid(),
    rejection_reason = null,
    updated_at = now()
  where id = submission_id;

  return created_student_id;
end;
$$;

revoke all on function public.approve_student_intake(bigint) from public;
grant execute on function public.approve_student_intake(bigint)
  to authenticated;

create or replace function public.reject_student_intake(
  submission_id bigint,
  reason text default null
)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if public.current_app_role() not in ('admin', 'receptionist') then
    raise exception 'Only active studio staff can reject registrations.';
  end if;

  update public."Student_Intake_Submissions"
  set
    status = 'Rejected',
    rejection_reason = nullif(trim(reason), ''),
    reviewed_at = now(),
    reviewed_by = auth.uid(),
    updated_at = now()
  where id = submission_id
    and status = 'Pending';

  if not found then
    raise exception 'Pending registration not found.';
  end if;
end;
$$;

revoke all on function public.reject_student_intake(bigint, text) from public;
grant execute on function public.reject_student_intake(bigint, text)
  to authenticated;

commit;
