-- Footloose Alley Studio Manager
-- v3.6.0: Production Authentication, Roles, RLS, and Error Logging
-- Run once in Supabase SQL Editor before using this release.

begin;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text not null,
  full_name text,
  role text not null default 'receptionist',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint profiles_role_check check (role in ('admin', 'receptionist'))
);

create table if not exists public.error_logs (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete set null default auth.uid(),
  message text not null,
  stack text,
  component_stack text,
  path text,
  user_agent text,
  created_at timestamptz not null default now()
);

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, email, full_name, role)
  values (
    new.id,
    coalesce(new.email, ''),
    nullif(new.raw_user_meta_data ->> 'full_name', ''),
    'receptionist'
  )
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

insert into public.profiles (id, email, full_name, role)
select
  id,
  coalesce(email, ''),
  nullif(raw_user_meta_data ->> 'full_name', ''),
  'receptionist'
from auth.users
on conflict (id) do nothing;

create or replace function public.claim_first_admin()
returns text
language plpgsql
security definer
set search_path = public
as $$
declare
  current_role text;
begin
  if auth.uid() is null then
    return null;
  end if;

  if not exists (select 1 from public.profiles where role = 'admin') then
    update public.profiles
    set role = 'admin', updated_at = now()
    where id = auth.uid();
  end if;

  select role into current_role
  from public.profiles
  where id = auth.uid();

  return current_role;
end;
$$;

create or replace function public.current_app_role()
returns text
language sql
stable
security definer
set search_path = public
as $$
  select role from public.profiles where id = auth.uid();
$$;

create or replace function public.set_staff_role(target_user uuid, new_role text)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if public.current_app_role() <> 'admin' then
    raise exception 'Only administrators can change staff roles.';
  end if;

  if new_role not in ('admin', 'receptionist') then
    raise exception 'Invalid staff role.';
  end if;

  if target_user = auth.uid() and new_role <> 'admin' then
    raise exception 'Administrators cannot remove their own admin access.';
  end if;

  update public.profiles
  set role = new_role, updated_at = now()
  where id = target_user;
end;
$$;

revoke all on function public.claim_first_admin() from public;
grant execute on function public.claim_first_admin() to authenticated;
revoke all on function public.current_app_role() from public;
grant execute on function public.current_app_role() to authenticated;
revoke all on function public.set_staff_role(uuid, text) from public;
grant execute on function public.set_staff_role(uuid, text) to authenticated;

alter table public.profiles enable row level security;
alter table public.error_logs enable row level security;

drop policy if exists profiles_select_authenticated on public.profiles;
create policy profiles_select_authenticated
  on public.profiles for select
  to authenticated
  using (id = auth.uid() or public.current_app_role() = 'admin');

drop policy if exists profiles_update_self on public.profiles;
create policy profiles_update_self
  on public.profiles for update
  to authenticated
  using (id = auth.uid())
  with check (id = auth.uid());

drop policy if exists error_logs_insert_authenticated on public.error_logs;
create policy error_logs_insert_authenticated
  on public.error_logs for insert
  to authenticated
  with check (user_id = auth.uid());

drop policy if exists error_logs_select_admin on public.error_logs;
create policy error_logs_select_admin
  on public.error_logs for select
  to authenticated
  using (public.current_app_role() = 'admin');

grant select on public.profiles to authenticated;
grant update (full_name, updated_at) on public.profiles to authenticated;
grant insert on public.error_logs to authenticated;
grant select on public.error_logs to authenticated;
grant usage, select on sequence public.error_logs_id_seq to authenticated;

do $$
declare
  table_name text;
  tables_to_secure text[] := array[
    'Students',
    'Attendance',
    'Payments',
    'Enquiries',
    'Instructors',
    'Classes',
    'Memberships',
    'Membership_Events',
    'fee_dues',
    'communication_history'
  ];
begin
  foreach table_name in array tables_to_secure loop
    if to_regclass(format('public.%I', table_name)) is not null then
      execute format('alter table public.%I enable row level security', table_name);

      execute format('drop policy if exists studio_select_staff on public.%I', table_name);
      execute format(
        'create policy studio_select_staff on public.%I for select to authenticated using (public.current_app_role() in (''admin'', ''receptionist''))',
        table_name
      );

      execute format('drop policy if exists studio_insert_staff on public.%I', table_name);
      execute format(
        'create policy studio_insert_staff on public.%I for insert to authenticated with check (public.current_app_role() in (''admin'', ''receptionist''))',
        table_name
      );

      execute format('drop policy if exists studio_update_staff on public.%I', table_name);
      execute format(
        'create policy studio_update_staff on public.%I for update to authenticated using (public.current_app_role() in (''admin'', ''receptionist'')) with check (public.current_app_role() in (''admin'', ''receptionist''))',
        table_name
      );

      execute format('drop policy if exists studio_delete_admin on public.%I', table_name);
      execute format(
        'create policy studio_delete_admin on public.%I for delete to authenticated using (public.current_app_role() = ''admin'')',
        table_name
      );

      execute format('grant select, insert, update, delete on public.%I to authenticated', table_name);
    end if;
  end loop;
end;
$$;

do $$
declare
  sequence_record record;
begin
  for sequence_record in
    select sequence_schema, sequence_name
    from information_schema.sequences
    where sequence_schema = 'public'
  loop
    execute format(
      'grant usage, select on sequence %I.%I to authenticated',
      sequence_record.sequence_schema,
      sequence_record.sequence_name
    );
  end loop;
end;
$$;

insert into storage.buckets (id, name, public)
values ('student-photos', 'student-photos', true)
on conflict (id) do update set public = excluded.public;

drop policy if exists student_photos_read_staff on storage.objects;
create policy student_photos_read_staff
  on storage.objects for select
  to authenticated
  using (bucket_id = 'student-photos');

drop policy if exists student_photos_insert_staff on storage.objects;
create policy student_photos_insert_staff
  on storage.objects for insert
  to authenticated
  with check (
    bucket_id = 'student-photos'
    and public.current_app_role() in ('admin', 'receptionist')
  );

drop policy if exists student_photos_update_staff on storage.objects;
create policy student_photos_update_staff
  on storage.objects for update
  to authenticated
  using (
    bucket_id = 'student-photos'
    and public.current_app_role() in ('admin', 'receptionist')
  )
  with check (
    bucket_id = 'student-photos'
    and public.current_app_role() in ('admin', 'receptionist')
  );

drop policy if exists student_photos_delete_admin on storage.objects;
create policy student_photos_delete_admin
  on storage.objects for delete
  to authenticated
  using (
    bucket_id = 'student-photos'
    and public.current_app_role() = 'admin'
  );

commit;
