-- Footloose Alley Studio Manager v5.4.0 instructor scheduling and payments.
begin;

create table if not exists public."Instructor_Sessions" (
 id bigint generated by default as identity primary key,
 class_id bigint not null references public."Classes"(id) on delete restrict,
 session_date date not null,
 assigned_instructor_id bigint not null references public."Instructors"(id) on delete restrict,
 substitute_instructor_id bigint references public."Instructors"(id) on delete restrict,
 status text not null default 'Scheduled', rate numeric(10,2) not null default 0,
 notes text, created_at timestamptz not null default now(), updated_at timestamptz not null default now(),
 constraint instructor_sessions_status_check check(status in ('Scheduled','Completed','Cancelled')),
 constraint instructor_sessions_rate_check check(rate >= 0),
 constraint instructor_sessions_unique unique(class_id,session_date)
);
create index if not exists instructor_sessions_instructor_date_idx on public."Instructor_Sessions"(assigned_instructor_id,session_date);
create index if not exists instructor_sessions_substitute_date_idx on public."Instructor_Sessions"(substitute_instructor_id,session_date);

create table if not exists public."Instructor_Payments" (
 id bigint generated by default as identity primary key,
 instructor_id bigint not null references public."Instructors"(id) on delete restrict,
 period_start date not null, period_end date not null, amount numeric(10,2) not null,
 status text not null default 'Pending', payment_method text, reference_number text, paid_at timestamptz, notes text,
 created_at timestamptz not null default now(), updated_at timestamptz not null default now(),
 constraint instructor_payments_period_check check(period_end >= period_start),
 constraint instructor_payments_amount_check check(amount > 0),
 constraint instructor_payments_status_check check(status in ('Pending','Paid','Cancelled'))
);
create index if not exists instructor_payments_instructor_period_idx on public."Instructor_Payments"(instructor_id,period_start desc);

alter table public."Instructor_Sessions" enable row level security;
alter table public."Instructor_Payments" enable row level security;
do $$ declare table_name text; begin foreach table_name in array array['Instructor_Sessions','Instructor_Payments'] loop
 execute format('drop policy if exists instructor_ops_select on public.%I',table_name);
 execute format('create policy instructor_ops_select on public.%I for select to authenticated using (public.current_app_role() in (''admin'',''receptionist''))',table_name);
 execute format('drop policy if exists instructor_ops_insert on public.%I',table_name);
 execute format('create policy instructor_ops_insert on public.%I for insert to authenticated with check (public.current_app_role() in (''admin'',''receptionist''))',table_name);
 execute format('drop policy if exists instructor_ops_update on public.%I',table_name);
 execute format('create policy instructor_ops_update on public.%I for update to authenticated using (public.current_app_role() in (''admin'',''receptionist'')) with check (public.current_app_role() in (''admin'',''receptionist''))',table_name);
 execute format('grant select,insert,update on public.%I to authenticated',table_name);
 end loop; end $$;

create or replace function public.save_instructor_session(p_id bigint,p_class_id bigint,p_session_date date,p_assigned bigint,p_substitute bigint,p_status text,p_rate numeric,p_notes text)
returns public."Instructor_Sessions" language plpgsql security invoker set search_path=public as $$
declare result public."Instructor_Sessions"; effective bigint; conflict bigint;
begin
 if public.current_app_role() not in ('admin','receptionist') then raise exception 'Staff access is required.' using errcode='42501'; end if;
 if p_status not in ('Scheduled','Completed','Cancelled') then raise exception 'Invalid session status.'; end if;
 effective:=coalesce(p_substitute,p_assigned);
 if p_substitute=p_assigned then raise exception 'Substitute must be a different instructor.'; end if;
 select s.id into conflict from public."Instructor_Sessions" s join public."Classes" existing_class on existing_class.id=s.class_id join public."Classes" requested_class on requested_class.id=p_class_id
 where s.session_date=p_session_date and s.status<>'Cancelled' and coalesce(s.substitute_instructor_id,s.assigned_instructor_id)=effective and (p_id is null or s.id<>p_id)
 and existing_class.start_time < requested_class.end_time and existing_class.end_time > requested_class.start_time limit 1;
 if conflict is not null then raise exception 'This instructor already has an overlapping session.'; end if;
 if p_id is null then insert into public."Instructor_Sessions"(class_id,session_date,assigned_instructor_id,substitute_instructor_id,status,rate,notes) values(p_class_id,p_session_date,p_assigned,p_substitute,p_status,round(p_rate,2),nullif(trim(coalesce(p_notes,'')),'')) returning * into result;
 else update public."Instructor_Sessions" set class_id=p_class_id,session_date=p_session_date,assigned_instructor_id=p_assigned,substitute_instructor_id=p_substitute,status=p_status,rate=round(p_rate,2),notes=nullif(trim(coalesce(p_notes,'')),''),updated_at=now() where id=p_id returning * into result; end if;
 return result;
end; $$;
revoke all on function public.save_instructor_session(bigint,bigint,date,bigint,bigint,text,numeric,text) from public,anon;
grant execute on function public.save_instructor_session(bigint,bigint,date,bigint,bigint,text,numeric,text) to authenticated;
commit;
