-- Footloose Alley Studio Manager
-- v3.3.0: WhatsApp Communication Center
-- Run this once in the Supabase SQL Editor before opening /whatsapp.

create table if not exists public.communication_history (
  id bigint generated by default as identity primary key,
  recipient_name text not null,
  phone text not null,
  recipient_type text not null,
  recipient_id bigint,
  category text not null,
  message text not null,
  status text not null default 'Opened in WhatsApp',
  sent_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);

alter table public.communication_history
  drop constraint if exists communication_history_recipient_type_check;

alter table public.communication_history
  add constraint communication_history_recipient_type_check
  check (recipient_type in ('Student', 'Enquiry'));

alter table public.communication_history
  drop constraint if exists communication_history_category_check;

alter table public.communication_history
  add constraint communication_history_category_check
  check (
    category in (
      'Fee Due',
      'Renewal',
      'Trial',
      'Attendance',
      'Birthday',
      'Enquiry',
      'Custom'
    )
  );

create index if not exists communication_history_sent_at_idx
  on public.communication_history (sent_at desc);

create index if not exists communication_history_recipient_idx
  on public.communication_history (recipient_type, recipient_id);

grant select, insert on public.communication_history to anon, authenticated;
grant usage, select on sequence public.communication_history_id_seq to anon, authenticated;
