begin;

create table if not exists public."Events" (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  title text not null,
  event_type text not null default 'Special Class',
  event_date date not null,
  start_time text not null,
  end_time text not null,
  location text not null default 'Footloose Alley',
  max_capacity integer not null default 50,
  fee numeric(10,2) not null default 0,
  status text not null default 'Upcoming',
  description text,
  contact_phone text default '8884978589',
  notes text,
  constraint events_event_type_check check (event_type in ('Workshop','Party','Outdoor','Special Class','Performance','Other')),
  constraint events_status_check check (status in ('Draft','Upcoming','Completed','Cancelled')),
  constraint events_capacity_check check (max_capacity between 1 and 10000),
  constraint events_fee_check check (fee >= 0)
);

create index if not exists events_event_date_idx on public."Events" (event_date);
create index if not exists events_status_idx on public."Events" (status);
alter table public."Events" enable row level security;

drop policy if exists events_select_staff on public."Events";
create policy events_select_staff on public."Events" for select to authenticated
  using (public.current_app_role() in ('admin', 'receptionist'));
drop policy if exists events_insert_staff on public."Events";
create policy events_insert_staff on public."Events" for insert to authenticated
  with check (public.current_app_role() in ('admin', 'receptionist'));
drop policy if exists events_update_staff on public."Events";
create policy events_update_staff on public."Events" for update to authenticated
  using (public.current_app_role() in ('admin', 'receptionist'))
  with check (public.current_app_role() in ('admin', 'receptionist'));
drop policy if exists events_delete_admin on public."Events";
create policy events_delete_admin on public."Events" for delete to authenticated
  using (public.current_app_role() = 'admin');

grant select, insert, update, delete on table public."Events" to authenticated;
grant usage, select on sequence public."Events_id_seq" to authenticated;

commit;
